/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;
import ClassDatabase.ClassDatabase;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Fadhil Cahya Hilmi
 */
public class EntriDataPenjualanACC extends javax.swing.JInternalFrame {

    /**
     * Creates new form EntriDataPenjualanACC
     */
    public EntriDataPenjualanACC() {
        super("Menu From Data Penjualan |Administrator Fadhil Cahya Hilmi");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kodeAccTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        qtyTF = new javax.swing.JTextField();
        tanggalTF = new com.toedter.calendar.JDateChooser();
        hargaTF = new javax.swing.JTextField();
        namaAccTF = new javax.swing.JTextField();
        stokTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORM ENTRI DATA PENJUALAN ACC");
        jLabel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Kode Acc");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Nama Acc");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Harga");

        kodeAccTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                kodeAccTFCaretUpdate(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Stok");

        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        closeBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        closeBtn.setText("CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "No. Pembelian", "Kode Barang", "Jumlah Beli", "Tanggal Beli", "Kode Supplier"
            }
        ));
        jScrollPane3.setViewportView(tabelData);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Qty");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Tanggal");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Total");

        qtyTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                qtyTFCaretUpdate(evt);
            }
        });

        tanggalTF.setDateFormatString("dd-MM-yyyy");

        hargaTF.setEditable(false);
        hargaTF.setBackground(new java.awt.Color(204, 204, 255));

        namaAccTF.setEditable(false);
        namaAccTF.setBackground(new java.awt.Color(204, 204, 255));

        stokTF.setEditable(false);
        stokTF.setBackground(new java.awt.Color(204, 204, 255));

        totalTF.setEditable(false);
        totalTF.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kodeAccTF)
                            .addComponent(hargaTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(namaAccTF)
                            .addComponent(stokTF))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtyTF)
                            .addComponent(tanggalTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalTF))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(closeBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kodeAccTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(namaAccTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveBtn)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodeAccTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_kodeAccTFCaretUpdate
        try {
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM master where kode_barang = '" + this.kodeAccTF.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()){
                this.namaAccTF.setText(r.getString("nama"));
                this.hargaTF.setText(r.getString("harga_jual"));
                this.stokTF.setText(r.getString("stok"));
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }
    }//GEN-LAST:event_kodeAccTFCaretUpdate

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        kodeAccTF.setText("");
        kodeAccTF.setText("");
        hargaTF.setText("");
        qtyTF.setText("");
        tanggalTF.setDate(null);
        namaAccTF.setText("");
        kodeAccTF.requestFocus();
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
       int id = 0, harga_beli = 0, harga_jual = 0, harga_total = 0, saham = 0, profit = 0;

        java.util.Date tanggal_beli = (java.util.Date) this.tanggalTF.getDate();
        String kode = this.kodeAccTF.getText();
        String nama = this.namaAccTF.getText();
        int harga_jual1 = Integer.parseInt(hargaTF.getText());
        int stok = Integer.parseInt(stokTF.getText());
        int jumlah_beli1 = Integer.parseInt(qtyTF.getText());
        int harga_total1 = Integer.parseInt(totalTF.getText());
        
        try{
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM master WHERE kode_barang = '" + this.kodeAccTF.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            while (r.next()){
                harga_beli = (r.getInt("harga_beli"));
                harga_jual = (r.getInt("harga_jual"));
                saham = (r.getInt("saham"));
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }
        
        profit = (harga_jual - harga_beli) * Integer.parseInt(qtyTF.getText());
        harga_total = jumlah_beli1 * harga_jual1;
        
        stokTF.setText(Integer.toString(stok));
        qtyTF.setText(Integer.toString(jumlah_beli1));
        String total = Integer.toString(harga_total);
        String jumlah_beli = this.qtyTF.getText();
        
        if (kodeAccTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor Pembelian Tidak Boleh Kosong");
        } else {
            if (qtyTF.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Kode Barang Tidak Boleh Kosong");
            }
            else {
                if (qtyTF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Jumlah Pembelian Tidak Boleh Kosong");
                }
                else {
                    if (totalTF.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Kode Supplier Tidak Boleh Kosong");
                    }
                    else {
                        try {
                            Connection c = ClassDatabase.getkoneksi();
                            String sql = "INSERT INTO penjualan values (?, ?, ?, ?, ?, ?)";
                            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                            p.setInt(1, id);
                            p.setString(2, kode);
                            p.setString(3, jumlah_beli);
                            p.setString(4, total);
                            p.setDate(5, new java.sql.Date(tanggal_beli.getTime()));
                            p.setInt(6,profit);
                            p.executeUpdate();
                            p.close();
                            JOptionPane.showMessageDialog(this,"Sukses Tambah Data");
                        } catch (SQLException e){
                            System.out.println(e);
                        } finally {
                        }
                    }
                }
            }
            try {
                Connection c = ClassDatabase.getkoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT kodea, qty, total, tgl_jual, profit FROM penjualan";
                ResultSet r = s.executeQuery(sql);
                tabelData.setModel(DbUtils.resultSetToTableModel(r));
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        String kodebrg = this.kodeAccTF.getText();
        
        int stok2 = Integer.parseInt(stokTF.getText());
        int jumlah_beli2 = Integer.parseInt(qtyTF.getText());
        int update_barang = 0;
        
        update_barang = stok2 - jumlah_beli2;
        saham = update_barang * harga_beli;
        
        String saham1 = Integer.toString(saham);
        String update_barang1 = Integer.toString(update_barang);
        
        try {
            Connection c = ClassDatabase.getkoneksi();
            String sql = "UPDATE master SET stok =?, saham =? WHERE kode_barang =?";
            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
            p.setString(3, kode);
            p.setString(1, update_barang1);
            p.setString(2, saham1);
            p.executeUpdate();
            p.close();
        } catch (SQLException e){
            System.out.println(e);
        } finally {
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        int ex = JOptionPane.showConfirmDialog(null, "Apakah Anda akan Keluar?", "Anda Yakin?",
            JOptionPane.YES_NO_OPTION);
        if (ex == 0) {
            dispose();
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void qtyTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_qtyTFCaretUpdate
        if(qtyTF.getText().isEmpty()){
            totalTF.setText("");
        } else {
            int harga_total = 0;
            int jumlah_beli = Integer.parseInt(qtyTF.getText());
            int harga_jual = Integer.parseInt(hargaTF.getText());
            
            harga_total = jumlah_beli * harga_jual;
            
            this.totalTF.setText(Integer.toString(harga_total));
        }
    }//GEN-LAST:event_qtyTFCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kodeAccTF;
    private javax.swing.JTextField namaAccTF;
    private javax.swing.JTextField qtyTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField stokTF;
    private javax.swing.JTable tabelData;
    private com.toedter.calendar.JDateChooser tanggalTF;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
