/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import ClassDatabase.ClassDatabase;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author danny
 */
public class FormEntri extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormEntri
     */
    public FormEntri() {
        super("Menu Form Pelanggan |Administrator Fadhil Cahya Hilmi");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        identitasBtn = new javax.swing.ButtonGroup();
        jeniskelaminBtn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        noidentitasTF = new javax.swing.JTextField();
        namaTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nohpTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        KTPBtn = new javax.swing.JRadioButton();
        SIMBtn = new javax.swing.JRadioButton();
        lakiBtn = new javax.swing.JRadioButton();
        perempuanBtn = new javax.swing.JRadioButton();
        cariBtn = new javax.swing.JButton();
        cariTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        alamatTF = new javax.swing.JTextArea();
        tanggalTF = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORM ENTRI DATA PELANGGAN");
        jLabel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("No. Identitas");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Alamat");

        noidentitasTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                noidentitasTFCaretUpdate(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("No. HP");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Tanggal");

        identitasBtn.add(KTPBtn);
        KTPBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        KTPBtn.setText("KTP");

        identitasBtn.add(SIMBtn);
        SIMBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SIMBtn.setText("SIM");

        jeniskelaminBtn.add(lakiBtn);
        lakiBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lakiBtn.setText("Laki-Laki");

        jeniskelaminBtn.add(perempuanBtn);
        perempuanBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        perempuanBtn.setText("Perempuan");

        cariBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cariBtn.setText("Cari Data");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        cariTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariTFKeyPressed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        editBtn.setText("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        closeBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        closeBtn.setText("CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Identitas", "Jenis Identitas", "Nama", "Alamat", "Jenis Kelamin", "No. HP", "Tanggal"
            }
        ));
        jScrollPane3.setViewportView(tabelData);

        alamatTF.setColumns(20);
        alamatTF.setRows(5);
        jScrollPane4.setViewportView(alamatTF);

        tanggalTF.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel2))
                                    .addGap(22, 22, 22))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lakiBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(perempuanBtn))
                                        .addComponent(nohpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namaTF)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(noidentitasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(KTPBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SIMBtn))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                        .addComponent(editBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(closeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cariBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noidentitasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KTPBtn)
                    .addComponent(SIMBtn)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(saveBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lakiBtn)
                            .addComponent(perempuanBtn)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nohpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cariBtn)
                        .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        noidentitasTF.setText("");
        namaTF.setText("");
        alamatTF.setText("");
        nohpTF.setText("");
        tanggalTF.setDate(null);
        identitasBtn.clearSelection();
        jeniskelaminBtn.clearSelection();
        noidentitasTF.requestFocus();
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        java.util.Date tgl_plg = (java.util.Date) this.tanggalTF.getDate();
        String no_identitas = this.noidentitasTF.getText();
        String nama = this.namaTF.getText();
        String j_identitas = null;
        if (KTPBtn.isSelected()){
            j_identitas = "KTP";
        } else if (SIMBtn.isSelected()){
            j_identitas = "SIM";
        }
        String jk = null;
        if (lakiBtn.isSelected()){
            jk = "Laki-Laki";
        } else if (perempuanBtn.isSelected()){
            jk = "Perempuan";
        }
        String alamat = this.alamatTF.getText();
        String nohp = this.nohpTF.getText();
        if (noidentitasTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor Identitas Pelanggan Tidak Boleh Kosong");
        } else {
            if (namaTF.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Nama Pelanggan Tidak Boleh Kosong");
            }
            else {
                if (alamatTF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Alamat Tidak Boleh Kosong");
                }
            else {
                if (nohpTF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Nomor HP Tidak Boleh Kosong");
                }   
            else {
                try {
                        Connection c = ClassDatabase.getkoneksi();
                        String sql = "INSERT INTO pelanggan values (?, ?, ?, ?, ?, ?, ?)";
                        PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                        p.setString(1, no_identitas);
                        p.setString(2, j_identitas);
                        p.setString(3, nama);
                        p.setString(4, alamat);
                        p.setString(5, jk);
                        p.setString(6, nohp);
                        p.setDate(7, new java.sql.Date(tgl_plg.getTime()));
                        p.executeUpdate();
                        p.close();
                        JOptionPane.showMessageDialog(this,"Sukses Tambah Data");
                    } catch (SQLException e){
                        System.out.println(e);
                    } finally {
                    }
                }
            }
        }
    }
        try {
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT no_identitas, j_identitas, nama, alamat, jk, nohp, tgl_plg FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(r));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        java.util.Date tgl_plg = (java.util.Date) this.tanggalTF.getDate();
        String no_identitas = this.noidentitasTF.getText();
        String nama = this.namaTF.getText();
        String j_identitas = null;
        if (KTPBtn.isSelected()){
            j_identitas = "KTP";
        } else if (SIMBtn.isSelected()){
            j_identitas = "SIM";
        }
        String jk = null;
        if (lakiBtn.isSelected()){
            jk = "Laki-Laki";
        } else if (perempuanBtn.isSelected()){
            jk = "Perempuan";
        }
        String alamat = this.alamatTF.getText();
        String nohp = this.nohpTF.getText();
        if (noidentitasTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor Identitas Pelanggan Tidak Boleh Kosong");
        } else {
            if (namaTF.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Pelanggan Tidak Boleh Kosong");
            }
        else {
            if (alamatTF.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Alamat Tidak Boleh Kosong");
            }
        else {
            if (nohpTF.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor HP Tidak Boleh Kosong");
            }    
            else {
                try {
                        Connection c = ClassDatabase.getkoneksi();
                        String sql = "UPDATE `fadhil`.`pelanggan` SET `j_identitas` = ?, `nama` = ?, `alamat` = ?, `jk` = ?, `nohp` = ?, `tgl_plg` = ? WHERE `no_identitas` = ?";
                        PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                        p.setString(7, no_identitas);
                        p.setString(1, j_identitas);
                        p.setString(2, nama);
                        p.setString(3, alamat);
                        p.setString(4, jk);
                        p.setString(5, nohp);
                        p.setDate(6, new java.sql.Date(tgl_plg.getTime()));
                        p.executeUpdate();
                        p.close();
                        JOptionPane.showMessageDialog(this,"Sukses Update Data");
                    } catch (SQLException e){
                        System.out.println(e);
                    } finally {
                    }
                }
            }
        }
    }
        try {
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT no_identitas, j_identitas, nama, jk, alamat, nohp, tgl_plg FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(r));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        
    }//GEN-LAST:event_editBtnActionPerformed

    private void noidentitasTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_noidentitasTFCaretUpdate
        try {
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan where no_identitas = '" + this.noidentitasTF.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()){
                this.namaTF.setText(r.getString(3));
                if ("KTP" .equalsIgnoreCase(r.getString("j_identitas"))){
                    KTPBtn.setSelected(true);
                } else {
                    SIMBtn.setSelected(true);
                }
                if ("Laki-Laki".equalsIgnoreCase(r.getString("jk"))){
                    lakiBtn.setSelected(true);
                } else {
                    perempuanBtn.setSelected(true);
                }
                this.alamatTF.setText(r.getString("alamat"));
                this.tanggalTF.setDate(r.getDate("tgl_plg"));
                this.nohpTF.setText(r.getString("nohp"));
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }
    }//GEN-LAST:event_noidentitasTFCaretUpdate

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        java.util.Date tgl_plg = (java.util.Date) this.tanggalTF.getDate();
        String no_identitas = this.noidentitasTF.getText();
        
        try {
            Connection c = ClassDatabase.getkoneksi();
            String sql = "DELETE FROM pelanggan WHERE no_identitas = ?";
            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
            p.setString(1, no_identitas);
            
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Hapus Data");
        } catch (SQLException e) {
            System.out.println(e);
        } finally {
        }
        
        try {
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT no_identitas, j_identitas, nama, alamat, jk, nohp, tgl_plg FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(r));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        int ex = JOptionPane.showConfirmDialog(null, "Apakah Anda akan Keluar?", "Anda Yakin?",
                JOptionPane.YES_NO_OPTION);
        if (ex == 0) {
            dispose();
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        DefaultTableModel tabelTampil1 = new DefaultTableModel();
        tabelTampil1.addColumn("no_identitas");
        tabelTampil1.addColumn("j_identitas");
        tabelTampil1.addColumn("nama");
        tabelTampil1.addColumn("alamat");
        tabelTampil1.addColumn("jk");
        tabelTampil1.addColumn("nohp");
        tabelTampil1.addColumn("tgl_plg");
        try {
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan WHERE no_identitas LIKE '%" + cariTF.getText() + "%'" +
                    "OR j_identitas LIKE '%" + cariTF.getText() + "%'" + "OR nama LIKE '%" + cariTF.getText() + "%'" +
                    "OR alamat LIKE '%" + cariTF.getText() + "%'" + "OR jk LIKE '%" + cariTF.getText() + "%'" +
                    "OR nohp LIKE '%" + cariTF.getText() + "%'" + "OR tgl_plg LIKE '%" + cariTF.getText() + "%'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                tabelTampil1.addRow(new Object[] {
                r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5),
                r.getString(6),
                r.getString(7),
            });}
            tabelData.setModel(tabelTampil1);
            } catch (Exception e){
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void cariTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTFKeyPressed
        DefaultTableModel tabelTampil1 = new DefaultTableModel();
        tabelTampil1.addColumn("no_identitas");
        tabelTampil1.addColumn("j_identitas");
        tabelTampil1.addColumn("nama");
        tabelTampil1.addColumn("alamat");
        tabelTampil1.addColumn("jk");
        tabelTampil1.addColumn("nohp");
        tabelTampil1.addColumn("tgl_plg");
        try {
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM pelanggan WHERE no_identitas LIKE '%" + cariTF.getText() + "%'" +
                    "OR j_identitas LIKE '%" + cariTF.getText() + "%'" + "OR nama LIKE '%" + cariTF.getText() + "%'" +
                    "OR alamat LIKE '%" + cariTF.getText() + "%'" + "OR jk LIKE '%" + cariTF.getText() + "%'" +
                    "OR nohp LIKE '%" + cariTF.getText() + "%'" + "OR tgl_plg LIKE '%" + cariTF.getText() + "%'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                tabelTampil1.addRow(new Object[] {
                r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5),
                r.getString(6),
                r.getString(7),
            });}
            tabelData.setModel(tabelTampil1);
            } catch (Exception e){
        }
    }//GEN-LAST:event_cariTFKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEntri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton KTPBtn;
    private javax.swing.JRadioButton SIMBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea alamatTF;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariTF;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.ButtonGroup identitasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.ButtonGroup jeniskelaminBtn;
    private javax.swing.JRadioButton lakiBtn;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField nohpTF;
    private javax.swing.JTextField noidentitasTF;
    private javax.swing.JRadioButton perempuanBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable tabelData;
    private com.toedter.calendar.JDateChooser tanggalTF;
    // End of variables declaration//GEN-END:variables
}
